services:
    postgres:
        image: postgres:17
        container_name: dev-postgres
        restart: unless-stopped
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: myapp
            POSTGRES_USER: myuser
            POSTGRES_PASSWORD: secret
        volumes:
            - pgdata:/var/lib/postgresql/data

    redis:
        image: redis:7-alpine
        container_name: dev-redis
        restart: unless-stopped
        ports:
            - "6379:6379"

volumes:
    pgdata:
